# Generated by Django 2.0.6 on 2018-06-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unique_words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
